name: Log Analysis
on:
  issue_comment:
    types: [created]

jobs:
  analyze:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/analyze') }}
    runs-on: self-hosted
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          if_key_exists: replace
          known_hosts: unnecessary
          config: |
            Host isuconapp
              HostName ${{ secrets.APP_HOST_NAME }}
              User root
              Port 22
              StrictHostKeyChecking no
              IdentityFile ~/.ssh/id_rsa
            Host isucondb
              HostName ${{ secrets.DB_HOST_NAME }}
              User root
              Port 22
              StrictHostKeyChecking no
              IdentityFile ~/.ssh/id_rsa
      - name: Analyze
        run: |
          ssh isucondb 'make mysql/pt-query-digest'
          ssh isucondb 'make mysql/mysqldumpslow'
          ssh isuconapp 'make nginx/alp'
      - name: Pull analysis result
        run: |
          rsync -av isucondb:~/pt_query_digest_analysis.txt ./
          rsync -av isucondb:~/mysqldumpslow_analysis.txt ./
          rsync -av isuconapp:~/alp_analysis.txt ./
      - name: Create pt-query-digest comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('pt_query_digest_analysis.txt', 'utf8');
            const body = `Analyze slow query log by pt-query-digest.
            <details>
            <summary>Show Output</summary>

            \`\`\`
            ${content}
            \`\`\`

            </details>`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body,
            });
      - name: Create mysqldumpslow comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('mysqldumpslow_analysis.txt', 'utf8');
            const body = `Analyze slow query log by mysqldumpslow.
            <details>
            <summary>Show Output</summary>

            \`\`\`
            ${content}
            \`\`\`

            </details>`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body,
            });
      - name: Create alp comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('alp_analysis.txt', 'utf8');
            const body = `Analyze access log by alp.
            <details>
            <summary>Show Output</summary>

            \`\`\`
            ${content}
            \`\`\`

            </details>`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body,
            });
